// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Paint } from "./Paint";

/**
 * Paint metadata to override default paints
 */
export type PaintOverride = { 
/**
 * Paints applied to characters
 */
fills: Array<Paint>, 
/**
 * ID of style node, if any, that this inherits fill data from
 */
inheritFillStyleId: string, };
