// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Enum describing the type of a paint
 */
export type PaintType = "Solid" | "GradientLienear" | "GradientRadial" | "GradientAngular" | "GradientDiamond" | "Image" | "Emoji" | "Video";
