// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Enum describing the semantic italic of TypeStyle
 */
export type TypeStyleSemanticItalic = "Italic" | "Normal";
