// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Enum describing the line heignt unit of TypeStyle
 */
export type TypeStyleLineHeightUnit = "Pixels" | "FontSize" | "Intrinsic";
