// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Enum describing the text horizontal align of TypeStyle
 */
export type TypeStyleTextAlignHorizontal = "Left" | "Right" | "Center" | "Justified";
