// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Enum describing the text vertical align of TypeStyle
 */
export type TypeStyleTextAlignVertical = "Top" | "Center" | "Bottom";
