// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Enum describing the text case of TypeStyle
 */
export type TypeStyleTextCase = "Upper" | "Lower" | "Title" | "SmallCaps" | "SmallCapsForced";
