// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Determines if the layer should stretch along the parent’s counter axis. This property is only provided for direct children of auto-layout frames.
 */
export type LayoutAlign = "Inherit" | "Stretch" | "Min" | "Center" | "Max";
