// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayoutConstraintHorizontal } from "./LayoutConstraintHorizontal";
import type { LayoutConstraintVertical } from "./LayoutConstraintVertical";

/**
 * Layout constraint relative to containing Frame
 */
export type LayoutConstraint = { 
/**
 * Vertical constraint as an enum
 */
vertical: LayoutConstraintVertical, 
/**
 * Horizontal constraint as an enum
 */
horizontal: LayoutConstraintHorizontal, };
