// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Enum describing horizontal layout constraint
 */
export type LayoutConstraintHorizontal = "Left" | "Right" | "Center" | "LeftRight" | "Scale";
