// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Enum describing the type of a simple transition
 */
export type SimpleTransitionType = "Dissolve" | "SmartAnimate" | "ScrollAnimate";
