// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Easing } from "../easing/Easing";
import type { SimpleTransitionType } from "./SimpleTransitionType";

/**
 * Describes an animation used when navigating in a prototype.
 */
export type SimpleTransition = { simpleTransitionType: SimpleTransitionType, 
/**
 * The duration of the transition in milliseconds.
 */
duration: number, 
/**
 * The easing curve of the transition.
 */
easing: Easing, };
