// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnnotationProperty } from "./AnnotationProperty";

/**
 * A note and pinned properties left on a node in Dev Mode
 */
export type Annotation = { label: string, properties: Array<AnnotationProperty>, };
