// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Enum describing AnnotationPropertyType
 */
export type AnnotationPropertyType = "Width" | "Height" | "Maxwidth" | "Minwidth" | "Maxheight" | "Minheight" | "Fills" | "Strokes" | "Effects" | "Strokeweight" | "Cornerradius" | "Textstyleid" | "Textalignhorizontal" | "Fontfamily" | "Fontstyle" | "Fontsize" | "Fontweight" | "Lineheight" | "Letterspacing" | "Itemspacing" | "Padding" | "Layoutmode" | "Alignitems" | "Opacity" | "Maincomponent";
