// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Information about the arc properties of an ellipse. 0° is the x axis and increasing angles
 * rotate clockwise
 */
export type ArcData = { 
/**
 * Start of the sweep in radians
 */
startingAngleNumber: number, 
/**
 * End of the sweep in radians
 */
endingAngle: number, 
/**
 * Inner radius value between 0 and 1
 */
innerRadius: number, };
