// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectorMagnet } from "./ConnectorMagnet";
import type { Vector } from "./Vector";

/**
 * Stores canvas location for a connector start/end point.
 */
export type ConnectorEndpoint = { 
/**
 * ConnectorEndpoint with endpointNodeId and position only:
 * Node ID this endpoint attaches to.
 */
endpointNodeId: string, 
/**
 * Canvas location as x & y coordinate.
 * ConnectorEndpoint with endpointNodeId and magnet only:
 */
position: Vector, 
/**
 * The magnet type is a string enum
 * AUTO
 * TOP
 * BOTTOM
 * LEFT
 * RIGHT
 */
magnet: ConnectorMagnet, };
