// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Paint } from "./paint/Paint";

/**
 * Connector text background.
 */
export type ConnectorTextBackground = { 
/**
 * Radius of each corner of the rectangle if a single radius is set for all corners
 */
cornerRadius: number, 
/**
 * An array of fill paints applied to the node
 */
fills: Array<Paint>, };
