// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DevStatusType } from "./DevStatusType";

/**
 * Represents a handoff (or dev) status applied to a node.
 */
export type DevStatus = { devStatusType: DevStatusType, 
/**
 * An optional field where the designer can add more information about the design and what has
 * changed.
 */
description: string, };
