// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a link to documentation for a component.
 */
export type DocumentationLink = { 
/**
 * Should be a valid URI (e.g. https://www.figma.com).
 */
uri: string, };
