// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Defines the list of operators available to use in an Expression.
 */
export type ExpressionFunction = "Addition" | "Subtraction" | "Multiplication" | "Division" | "Equals" | "Not" | "LessThan" | "LessThanOrEqual" | "GreaterThan" | "GreaterThanOrEqual" | "And" | "Or" | "VarModeLookup" | "Negate";
