// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Defines the image filters applied to an image paint. All values are from -1 to 1.
 */
export type ImageFilters = { 
/**
 * default: 0
 */
exposureNumber: number, 
/**
 * default: 0
 */
contrastNumber: number, 
/**
 * default: 0
 */
saturationNumber: number, 
/**
 * default: 0
 */
temperatureNumber: number, 
/**
 * default: 0
 */
tintNumber: number, 
/**
 * default: 0
 */
highlightsNumber: number, 
/**
 * default: 0
 */
shadowsNumber: number, };
