// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Defines the image filters applied to an image paint. All values are from -1 to 1.
 */
export type ImageFilters = { 
/**
 * default: 0
 */
exposure: number, 
/**
 * default: 0
 */
contrast: number, 
/**
 * default: 0
 */
saturation: number, 
/**
 * default: 0
 */
temperature: number, 
/**
 * default: 0
 */
tint: number, 
/**
 * default: 0
 */
highlights: number, 
/**
 * default: 0
 */
shadows: number, };
