// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Enum describing InstanceSwapPreferredValueType
 */
export type InstanceSwapPreferredValueType = "Component" | "ComponentSet";
