// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Defines a single path
 */
export type Path = { 
/**
 * A series of path commands that encodes how to draw the path.
 */
path: string, 
/**
 * The winding rule for the path (same as in SVGs). This determines whether a given point in
 * space is inside or outside the path.
 */
windingRule: string, 
/**
 * If there is a per-region fill, this refers to an ID in the fillOverrideTable.
 */
overrideId: number, };
