// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Enum desccribin PrototypeDeviceRotation
 */
export type PrototypeDeviceRotation = "None" | "CCW90";
