// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrototypeDeviceRotation } from "./PrototypeDeviceRotation";
import type { PrototypeDeviceType } from "./PrototypeDeviceType";
import type { Size } from "./Size";

/**
 * The device used to view a prototype
 */
export type PrototypeDevice = { prototypeDeviceType: PrototypeDeviceType, size: Size, 
/**
 * rotation'NONE' | 'CCW_90'
 */
presetIdentifier: string, rotation: PrototypeDeviceRotation, };
