// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A rectangle that expresses a bounding box in absolute coordinates
 */
export type Rectangle = { 
/**
 * X coordinate of top left corner of the rectangle
 */
x: number, 
/**
 * Y coordinate of top left corner of the rectangle
 */
y: number, 
/**
 * Width of the rectangle
 */
width: number, 
/**
 * Height of the rectangle
 */
height: number, };
