// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VariableData } from "./VariableData";

/**
 * An action that sets a variable to a specific value.
 */
export type SetVariableAction = { setVariableActionType: string, variableId?: string, variableValue: VariableData, };
