// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An action that sets a variable to a specific mode.
 */
export type SetVariableModeAction = { setVariableModeActionType: string, variableCollectionId: string | null, variableModeId: string | null, };
