// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Geometric shape type. Most shape types have the same name as their tooltip but there are a few exceptions. ENG_DATABASE: Cylinder, ENG_QUEUE: Horizontal cylinder, ENG_FILE: File, ENG_FOLDER: Folder.
 */
export type ShapeType = "Square" | "Ellipse" | "RoundedRectangle" | "Diamond" | "TriangleDown" | "ParallelogramRight" | "ParallelogramLeft" | "EngDatabase" | "EngQueue" | "EngFile" | "EngFolder" | "Trapezoid" | "PredefinedProcess" | "Shield" | "DocumentSingle" | "DocumentMultiple" | "ManualInput" | "Hexagon" | "Chevron" | "Pentagon" | "Octagon" | "Star" | "Plus" | "ArrowLeft" | "ArrowRight" | "SummingJunction" | "Or" | "SpeechBubble" | "InternalStorage";
