// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A width and a height
 */
export type Size = { 
/**
 * the width of a size
 */
width: number, 
/**
 * the height of a size
 */
height: number, };
