// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StyleType } from "./StyleType";

/**
 * A set of properties that can be applied to nodes and published. Styles for a property can be
 * created in the corresponding property's panel while editing a file
 */
export type Style = { 
/**
 * The key of the style
 */
key: string, 
/**
 * The name of the style
 */
name: string, 
/**
 * The description of the style
 */
description: string, 
/**
 * Whether this style is a remote style that doesn't live in this file
 */
remote: boolean, 
/**
 * The type of style as string enum
 * FILL
 * TEXT
 * EFFECT
 * GRID
 */
styleType: StyleType, };
