// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A 2x3 affine transformation matrix
 */
export type Transform = { 
/**
 * A 2D affine transformation matrix that can be used to calculate the affine transforms applied to a layer, including scaling, rotation, shearing, and translation.
 * The form of the matrix is given as an array of 2 arrays of 3 numbers each. E.g. the identity matrix would be    [[1, 0, 0],
 */
matrix: Array<Array<number>>, };
