// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColorType } from "./color/ColorType";
import type { Expression } from "./Expression";
import type { RGBColorType } from "./color/RGBColorType";
import type { VariableAlias } from "./VariableAlias";

/**
 * Enum decribing the value of a variable data
 */
export type VariableDataValue = { "Bool": boolean } | { "I32": number } | { "String": string } | { "Color": ColorType } | { "RGBColor": RGBColorType } | { "VariableAlias": VariableAlias } | { "Expression": Expression };
