// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A 2d vector
 */
export type Vector = { 
/**
 * X coordinate of the vector
 */
x: number, 
/**
 * Y coordinate of the vector
 */
y: number, };
