// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArcData } from "../../properties/ArcData";

/**
 * Specific data for ellipse.
 */
export type EllipseData = { 
/**
 * Start and end angles of the ellipse measured clockwise from the x axis, plus the inner
 * radius for donuts
 */
arcData: ArcData, };
