// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnnotationPropertyType } from "./AnnotationPropertyType";

/**
 * A pinned property in an Annotation
 */
export type AnnotationProperty = { annotation_property_type: AnnotationPropertyType, };
