// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Information about the arc properties of an ellipse. 0° is the x axis and increasing angles rotate clockwise
 */
export type ArcData = { 
/**
 * Start of the sweep in radians
 */
starting_angle_number: number, 
/**
 * End of the sweep in radians
 */
ending_angle: number, 
/**
 * Inner radius value between 0 and 1
 */
inner_radius: number, };
