// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color";
import type { VariableAlias } from "./VariableAlias";

/**
 * A stop in a gradient paint that contains information about the stop position, color, and bound variables
 */
export type ColorStop = { 
/**
 * Value between 0 and 1 representing position along gradient axis
 */
position: number, 
/**
 * Color attached to corresponding position
 */
color: Color, 
/**
 * Color variable that is attached to the stop if any
 */
boundVariables: { [key in string]?: VariableAlias }, };
