// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentPropertyDefinitionDefaultValue } from "./ComponentPropertyDefinitionDefaultValue";
import type { ComponentPropertyType } from "./ComponentPropertyType";
import type { InstanceSwapPreferredValue } from "./InstanceSwapPreferredValue";

/**
 * Component property definition
 */
export type ComponentPropertyDefinition = { 
/**
 * Type of this component property
 */
componentType: ComponentPropertyType, 
/**
 * Initial value of this property for instances
 */
defaultValue: ComponentPropertyDefinitionDefaultValue, 
/**
 * All possible values for this property. Only exists on VARIANT properties
 */
variantOptions: Array<string>, 
/**
 * List of user-defined preferred values for this property. Only exists on INSTANCE_SWAP properties
 */
preferredValues: Array<InstanceSwapPreferredValue>, };
