// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocumentationLink } from "./DocumentationLink";

/**
 * A description of a component set, which is a node containing a set of variants of a component
 */
export type ComponentSet = { 
/**
 * The key of the component set
 */
key: string, 
/**
 * The name of the component set
 */
name: string, 
/**
 * The description of the component set as entered in the editor
 */
description: string, 
/**
 * The documentation links for this component set.
 */
documentationLinks: Array<DocumentationLink>, 
/**
 * Whether this component set is a remote component set that doesn't live in this file
 */
remote: boolean, };
