// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConditionalBlock } from "./ConditionalBlock";

/**
 * An action that checks if a condition is met before performing certain actions by using an if/else conditional statement.
 */
export type ConditionalAction = { conditionalActionType: string, conditionalBlocks: Array<ConditionalBlock>, };
