// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Enum describing type of constraint
 */
export type ConstraintType = "Scale" | "Width" | "Height";
