// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Node } from "./Node";

export type DocumentNode = { 
/**
 * An array of canvases attached to the document.
 */
children: Array<Node>, };
