// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Constraint } from "./Constraint";
import type { FormatType } from "./FormatType";

/**
 * Format and size to export an asset at
 */
export type ExportSetting = { 
/**
 * File suffix to append to all filenames
 */
suffix: string, 
/**
 * Image type, string enum that supports values JPG, PNG, and SVG
 */
format: FormatType, 
/**
 * Constraint that determines sizing of exported asset
 */
constraint: Constraint, };
