// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A flow starting point used when launching a prototype to enter Presentation view.
 */
export type FlowStartingPoint = { 
/**
 * Unique identifier specifying the frame
 */
nodeId: string, 
/**
 * Name of flow
 */
name: string, };
