// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstanceSwapPreferredValueType } from "./InstanceSwapPreferredValueType";

/**
 * Instance swap preferred value
 */
export type InstanceSwapPreferredValue = { 
/**
 * Type of node for this preferred value
 */
istance_swap_preferred_value_type: InstanceSwapPreferredValueType, 
/**
 * Key of this component or component set
 */
key: string, };
