// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Action } from "./Action";
import type { Trigger } from "./Trigger";

/**
 * An interaction in the Figma viewer, containing a trigger and one or more actions.
 */
export type Interaction = { 
/**
 * The user event that initiates the interaction.
 */
trigger: Trigger | null, 
/**
 * The actions that are performed when the trigger is activated.
 */
actions: Array<Action>, };
