// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayoutHorizontalConstraint } from "./LayoutHorizontalConstraint";
import type { LayoutVerticalConstraint } from "./LayoutVerticalConstraint";

/**
 * Layout constraint relative to containing Frame
 */
export type LayoutConstraint = { 
/**
 * Vertical constraint as an enum
 */
vertical: LayoutVerticalConstraint, 
/**
 * Horizontal constraint as an enum
 */
horizontal: LayoutHorizontalConstraint, };
