// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Enum describing how mask layer operates on the pixels of the layers it masks.
 */
export type MaskType = "Alpha" | "Vector" | "Luminance";
