// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MeasurementOffsetInner } from "./MeasurementOffsetInner";
import type { MeasurementOffsetOuter } from "./MeasurementOffsetOuter";

/**
 * Enum describing the offest of a Measurement
 */
export type MeasurementOffset = { "measurementOffsetInner": MeasurementOffsetInner } | { "measurementOffsetOuter": MeasurementOffsetOuter };
