// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CanvasNode } from "./CanvasNode";
import type { DocumentNode } from "./DocumentNode";
import type { VectorNode } from "./VectorNode";

export type NodeType = { "Document": DocumentNode } | { "Canvas": CanvasNode } | { "Vector": VectorNode };
