// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Fields directly overridden on an instance. Inherited overrides are not included.
 */
export type Overrides = { 
/**
 * A unique ID for a node
 */
id: string, 
/**
 * An array of properties
 */
overriddenFields: Array<string>, };
