// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RectangleNode = { cornerRadius: number, rectangleCornerRadii: [number, number, number, number], cornerSmoothing: number, };
