// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Individual stroke weights
 */
export type StrokeWeights = { 
/**
 * The top stroke weight
 */
top: number, 
/**
 * The right stroke weight
 */
right: number, 
/**
 * The bottom stroke weight
 */
bottom: number, 
/**
 * The left stroke weight
 */
left: number, };
