// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Enum describing the media action of UpdateMediaRuntimeAction
 */
export type UpdateMediaRuntimeActionMediaAction = "Play" | "Pause" | "TogglePlayPause" | "Mute" | "Unmute" | "ToggleMuteUnmute" | "SkipForward" | "SkipBackward" | "SkipTo";
