// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VariableDataType } from "./VariableDataType";
import type { VariableDataValue } from "./VariableDataValue";
import type { VariableResolvedDataType } from "./VariableResolvedDataType";

/**
 * A value to set a variable to during prototyping.
 */
export type VariableData = { variableDataType: VariableDataType, resolvedType: VariableResolvedDataType, value: VariableDataValue, };
