// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Defines the types of data a VariableData object can eventually equal.
 */
export type VariableResolvedDataType = "Boolean" | "Float" | "String" | "Color";
