// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color";
import type { Expression } from "./Expression";
import type { RGBColor } from "./RGBColor";
import type { VariableAlias } from "./VariableAlias";

/**
 * Enum decribing the value of a variable data
 */
export type VariableDataValue = { "Bool": boolean } | { "I32": number } | { "String": string } | { "Color": Color } | { "RGBColor": RGBColor } | { "VariableAlias": VariableAlias } | { "Expression": Expression };
