// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlendMode } from "./BlendMode";
import type { LayoutConstraint } from "./LayoutConstraint";
import type { Rectangle } from "./Rectangle";

export type VectorNode = { 
/**
 * If true, layer is locked and cannot be edited.
 */
locked: boolean, blendMode: BlendMode, 
/**
 * Keep height and width constrained to same ratio
 */
preserveRatio: boolean, layoutGrow: number, constraint: LayoutConstraint, opacity: number, absoluteBoundingBox: Rectangle, absoluteRenderBounds: Rectangle | null, strokeWeight: number, strokeDashes: Array<number>, };
