// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlendMode } from "./BlendMode";
import type { Effect } from "./Effect";
import type { LayoutConstraint } from "./LayoutConstraint";
import type { Paint } from "./Paint";
import type { Path } from "./Path";
import type { Rectangle } from "./Rectangle";
import type { Size } from "./Size";
import type { StrokeWeights } from "./StrokeWeights";

export type VectorNode<Data> = { 
/**
 * If true, layer is locked and cannot be edited.
 */
locked: boolean, blendMode: BlendMode, 
/**
 * Keep height and width constrained to same ratio
 */
preserveRatio: boolean, layoutGrow: number, constraint: LayoutConstraint, opacity: number, 
/**
 * Bounding box of the node in absolute space coordinates
 */
absoluteBoundingBox: Rectangle, 
/**
 * The actual bounds of a node accounting for drop shadows, thick strokes, and anything else that may fall outside the node's regular bounding box defined in x, y, width, and height. The x and y inside this property represent the absolute position of the node on the page. This value will be null if the node is invisible.
 */
absoluteRenderBounds: Rectangle | null, effects: Array<Effect>, size: Size, fills: Array<Paint>, fillGeometry: Array<Path>, strokes: Array<Paint>, strokeWeight: number, individualStrokeWeights: StrokeWeights, strokeDashes: Array<number>, strokeGeometry: Array<Path>, addidionalData: Data, };
