// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VectorNode = { 
/**
 * If true, layer is locked and cannot be edited.
 */
locked: boolean, 
/**
 * Keep height and width constrained to same ratio
 */
preserve_ratio: boolean, layout_grow: number, opacity: number, stroke_weight: number, stroke_dashes: Array<number>, };
