// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A cubic bezier curve that defines the easing.
 */
export type EasingFunctionCubicBezier = { 
/**
 * The x component of the first control point.
 */
x1: number, 
/**
 * The y component of the first control point.
 */
y1: number, 
/**
 * The x component of the second control point.
 */
x2: number, 
/**
 * The y component of the second control point.
 */
y2: number, };
