// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A spring function that defines the easing.
 */
export type EasingFunctionSpring = { mass: number, stiffness: number, damping: number, };
