// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An RBG Color
 */
export type RGBColorType = { 
/**
 * Red channel value, between 0 and 1
 */
r: number, 
/**
 * Green channel value, between 0 and 1
 */
g: number, 
/**
 * Blue channel value, between 0 and 1
 */
b: number, };
