// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Measurement offset relative to the inside of the start node
 */
export type MeasurementOffsetInner = { measurementOffsetInnerType: string, relative: number, };
