// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MeasurementOffset } from "./MeasurementOffset";
import type { MeasurementStartEnd } from "./MeasurementStartEnd";

/**
 * A pinned distance between two nodes in Dev Mode
 */
export type Measurement = { id: string, start: MeasurementStartEnd, end: MeasurementStartEnd, offset: MeasurementOffset, 
/**
 * When manually overridden, the displayed value of the measurement
 */
freeText: string, };
