// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MeasurementStartEndSide } from "./MeasurementStartEndSide";

/**
 * The node and side a measurement is pinned to
 */
export type MeasurementStartEnd = { nodeId: string, side: MeasurementStartEndSide, };
