// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Measurement offset relative to the outside of the start nod
 */
export type MeasurementOffsetOuter = { measurementOffsetOuterType: string, relative: number, };
