// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColorType } from "../properties/color/ColorType";
import type { Node } from "./Node";

export type CanvasNode = { 
/**
 * An array of top level layers on the canvas
 */
children: Array<Node>, backgroundColor: ColorType, };
