// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CanvasNode } from "./CanvasNode";
import type { DocumentNode } from "./DocumentNode";
import type { EmptyData } from "./vector/EmptyData";
import type { RectangleData } from "./vector/RectangleData";
import type { VectorNode } from "./vector/VectorNode";

export type NodeType = { "type": "document", "data": DocumentNode } | { "type": "canvas", "data": CanvasNode } | { "type": "vector", "data": VectorNode<EmptyData> } | { "type": "rectangle", "data": VectorNode<RectangleData> };
