// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeType } from "../NodeType";

export type Node = { 
/**
 * A string uniquely identifying this node within the document.
 */
id: string, 
/**
 * The name given to the node by the user in the tool.
 */
name: string, 
/**
 * Whether or not the node is visible on the canvas.
 */
visible: boolean, 
/**
 * The type of the node.
 */
node: NodeType, 
/**
 * The rotation of the node, if not 0.
 */
rotation: number, };
