// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An action that opens a URL.
 */
export type OpenURLAction = { openUrlActionType: string, url: string, };
