// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Enum describing the device of a trigger
 */
export type TriggerDevice = "keyboard" | "xboxOne" | "ps4" | "switchPro" | "unknownController";
