// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Enum describing the type of a trigger,
 */
export type TriggerType = "OnClick" | "OnHover" | "OnPress" | "OnDrag" | "AfterTimeout" | "MouseEnter" | "MouseLeave" | "MouseUp" | "MouseDown" | "OnMediaEnd" | "OnKeyDown" | "OnKeyUp" | "OnMediaHit";
