// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpdateMediaRuntimeActionMediaAction } from "./UpdateMediaRuntimeActionMediaAction";

/**
 * An action that affects a video node in the Figma viewer. For example, to play, pause, or skip.
 */
export type UpdateMediaRuntimeAction = { updateMediaRuntimeType: string, 
/**
 * The node ID of the media node to update. If destinationId is null, the action will update the media node that contains the action.
 */
destinationId: string | null, 
/**
 * The action to perform on the media node.
 */
mediaAction: UpdateMediaRuntimeActionMediaAction, 
/**
 * For "SKIP_FORWARD" and "SKIP_BACKWARDS" actions:
 * The amount of time to skip in seconds.
 */
amountToSkip: number, 
/**
 * For SKIP_TO actions:
 * The new time to skip to in seconds.
 */
newTimestamp: number, };
