// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentPropertyType } from "./ComponentPropertyType";
import type { ComponentPropertyValue } from "./ComponentPropertyValue";
import type { InstanceSwapPreferredValue } from "../InstanceSwapPreferredValue";
import type { VariableAlias } from "../VariableAlias";

/**
 * Component property
 */
export type ComponentProperty = { 
/**
 * Type of this component property
 */
componentPropertyType: ComponentPropertyType, 
/**
 * Value of this property set on this instance
 */
value: ComponentPropertyValue, 
/**
 * List of user-defined preferred values for this property. Only exists on INSTANCE_SWAP
 * properties
 */
preferredValues: Array<InstanceSwapPreferredValue>, 
/**
 * A mapping of field to the VariableAlias of the bound variable.
 */
boundVariables: { [key in string]?: VariableAlias }, };
