// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Component property type
 */
export type ComponentPropertyType = "Boolean" | "InstanceSwap" | "Text" | "Variant";
