// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A string enum with values describing the end caps of vector paths.
 */
export type StrokeCap = "None" | "Round" | "Square" | "LineArrow" | "TriangleArrow" | "DiamondFilled" | "CircleFilled" | "TriangleFilled" | "WashiTape1" | "WashiTape2" | "WashiTape3" | "WashiTape4" | "WashiTape5" | "WashiTape6";
