// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Position of stroke relative to vector outline, as a string enum
 */
export type StrokeAlign = "Inside" | "Outside" | "Center";
